---
title: Result/Try
---
import Exercise from "../../../../src/components/exercise/Exercise";
import GitHubRepoLink from "../../../../src/components/GithubRepoLink";
import ReadingTime from "../../../../src/components/ReadingTime";
import Solution from "../../../../src/components/exercise/Solution";

<ReadingTime/>
<GitHubRepoLink repo={"functional-programming-kt"} user={"r8vnhill"}/>

<br/>
La mónada **Result** (o **Try** en algunos lenguajes) se utiliza para encapsular operaciones que pueden fallar, representando tanto el éxito como el fallo de manera explícita y segura.

## Componentes Principales:

- **Success** (o **Ok** en algunos lenguajes):
    - Representa un resultado exitoso de la operación.
    - Contiene el valor resultante de la operación.

- **Failure** (o **Err** en algunos lenguajes):
    - Representa un fallo o error durante la operación.
    - Contiene la excepción o un mensaje que describe el error.

## Motivación:

1. **Evita excepciones no controladas**: Result permite manejar errores de forma explícita sin depender de excepciones lanzadas que puedan ser ignoradas o propagadas accidentalmente.
2. **Manejo de errores más seguro**: Obliga a lx desarrolladorx a manejar ambos casos (éxito y fallo), previniendo errores no gestionados y haciendo el código más robusto.
3. **Flujo de control más claro**: Al hacer explícitos los casos de éxito y fallo, se facilita la composición de funciones y se mejora la legibilidad y seguridad del código.

## Implementación

En Kotlin, podemos implementar la mónada Result utilizando una clase sellada que contenga dos subclases: `Success` y `Failure`. Cada subclase puede contener el valor resultante o el error, respectivamente.

```kotlin title="monads/src/main/kotlin/cl/ravenhill/result/Result.kt" showLineNumbers
package cl.ravenhill.result

sealed class Result<out T> {
    inline fun <U> flatMap(f: (T) -> Result<U>) = when (this) {
        is Failure -> this
        is Success -> f(value)
    }

    companion object {
        fun <T> pure(value: T) = Success(value)
    }
}
```

```kotlin title="monads/src/main/kotlin/cl/ravenhill/result/Success.kt" showLineNumbers
package cl.ravenhill.result

data class Success<out T>(val value: T) : Result<T>()
```

```kotlin title="monads/src/main/kotlin/cl/ravenhill/result/Failure.kt" showLineNumbers
package cl.ravenhill.result

data class Failure(val error: Throwable) : Result<Nothing>()
```

:::note
En este caso implementamos la mónada ``Result`` para fines didácticos, pero Kotlin ya proporciona una implementación dentro de su biblioteca estándar.
:::

<Exercise title={"Extensiones de Result"}>
    1. Implementa una función `runCatching: (() -> T) -> Result<T>` que envuelva una operación en un bloque seguro. Esta función debe devolver un `Success` con el resultado de tipo `T` si la operación se completa sin excepciones. Si se lanza alguna excepción, la función debe devolver un `Failure` con la excepción capturada.
    2. Implementa una función `fold: (Result<T>, (Throwable) -> U, (T) -> U) -> U`, que permita procesar un resultado de forma segura. La función toma dos lambdas: la primera se ejecuta en caso de un error (`Failure`), y la segunda se ejecuta en caso de éxito (`Success`). La función debe devolver el valor que resulte de ejecutar la lambda correspondiente.

    <Solution>
        ```kotlin title="monads/src/main/kotlin/cl/ravenhill/result/ResultExtensions.kt" showLineNumbers
        @Suppress("TooGenericExceptionCaught")
        inline fun <T> runCatching(block: () -> T): Result<T> = try {
            Success(block())
        // highlight-next-line
        } catch (e: Throwable) {
            Failure(e)
        }

        inline fun <T, U> fold(
            result: Result<T>,
            onFailure: (Throwable) -> U,
            onSuccess: (T) -> U
        ) = when (result) {
            is Failure -> onFailure(result.error)
            is Success -> onSuccess(result.value)
        }
        ```

        :::note
        En general es una mala práctica capturar excepciones genéricas, pero para poder implementar la función ``runCatching`` necesitamos que cubra todos los tipos de errores. La anotación `@Suppress("TooGenericExceptionCaught")` evita que la compilación falle por faltas a las reglas de Detekt. Es importante tener en cuenta que esta anotación debe usarse con precaución y solo en casos donde sea estrictamente necesario.
        :::
    </Solution>
</Exercise>

## Comparación con `Either`

Tanto `Result` como `Either` son tipos que nos permiten manejar operaciones que pueden fallar, pero existen algunas diferencias clave entre ellos:

### Similitudes:

- **Manejo explícito de errores**: Ambos tipos hacen que el manejo de errores sea más explícito, evitando el uso de excepciones no controladas.
- **Composición**: Tanto `Result` como `Either` permiten encadenar operaciones de forma segura mediante el uso de métodos como `flatMap`, lo que facilita el manejo de errores sin necesidad de `try-catch`.
- **Estructura básica**: Ambos tipos tienen dos posibles resultados. En `Result`, los casos son `Success` y `Failure`, mientras que en `Either` son `Right` (para éxito) y `Left` (para fallo).

### Diferencias:

- **Semántica**: `Either` es un tipo más general, utilizado para representar una elección entre dos valores, no necesariamente relacionado con errores. `Result` está diseñado específicamente para modelar operaciones que pueden fallar, con el éxito representado por `Success` y el fallo por `Failure`.
- **Información del Error**: En `Result`, el caso de fallo (`Failure`) generalmente contiene una excepción (`Throwable`), mientras que en `Either`, el `Left` puede contener cualquier tipo de dato, permitiendo más flexibilidad en la información que se proporciona sobre el error.

### Ejemplo en Kotlin usando `Either` y `Result`

Veamos cómo podríamos manejar una operación que puede fallar utilizando ambos tipos empleando `flatMap` y `pure`.

#### Usando `Either`

```kotlin showLineNumbers
fun divideEither(a: Int, b: Int): Either<String, Int> = if (b == 0) {
    Left("Cannot divide by zero")
} else {
    Right(a / b)
}

fun multiplyByTwo(value: Int): Either<String, Int> = Right(value * 2)

val resultEither = divideEither(10, 2)
    .flatMap { value -> multiplyByTwo(value) }

when (resultEither) {
    is Left -> println("Error: ${resultEither.value}")
    is Right -> println("Success: ${resultEither.value}")
}
```

#### Usando `Result`

```kotlin showLineNumbers
fun divideResult(a: Int, b: Int): Result<Int> = if (b == 0)
    Failure(IllegalArgumentException("Cannot divide by zero"))
else {
    Success(a / b)
}

fun multiplyByTwoResult(value: Int): Result<Int> = Result.pure(value * 2)

val resultResult = divideResult(10, 2)
    .flatMap { value -> multiplyByTwoResult(value) }

when (resultResult) {
    is Failure -> println("Error: ${resultResult.error.message}")
    is Success -> println("Success: ${resultResult.value}")
}
```

En ambos ejemplos:

- Definimos una función `divide` que puede fallar si se intenta dividir por cero.
- Usamos `flatMap` para encadenar otra operación (`multiplyByTwo`) que se ejecutará solo si la operación anterior tuvo éxito.
- Empleamos `when` para manejar los casos de éxito y error de manera explícita, sin utilizar `fold`.

Aunque `Either` y `Result` pueden parecer similares y se pueden usar de manera intercambiable en algunos casos, la elección entre uno u otro depende del contexto y las necesidades específicas:

- Si necesitas un tipo general para representar una elección entre dos valores que no necesariamente implican éxito o error, `Either` es más apropiado.
- Si estás manejando operaciones que pueden lanzar excepciones y deseas capturarlas y manejarlas de manera funcional, `Result` es la opción indicada.

Ambos tipos mejoran la seguridad y claridad del código al evitar excepciones no controladas y al hacer explícito el manejo de errores. Además, al utilizar funciones como `flatMap` y `pure`, podemos componer operaciones de manera limpia y manejable.

## ¿Qué hemos visto?

En esta lección, hemos aprendido a utilizar **Result** y **Either** para manejar operaciones que pueden fallar de manera segura y explícita. A lo largo de la lección, vimos:

- **Componentes clave de Result**: cómo `Success` y `Failure` encapsulan el éxito y el fallo de una operación.
- **Motivación**: cómo estos enfoques mejoran el manejo de errores al evitar excepciones no controladas, haciendo el código más robusto y claro.
- **Implementación en Kotlin**: cómo implementar y usar `Result` y `Either` de manera funcional, utilizando métodos como `flatMap` y `pure` para encadenar operaciones sin necesidad de `try-catch`.
- **Comparación**: exploramos las diferencias y similitudes entre `Result` y `Either`, considerando cuándo es más adecuado usar uno u otro.

Al final, comprendimos cómo ambos tipos nos permiten manejar errores de manera clara, explícita y funcional, lo que facilita la composición y mejora la seguridad del código.

Ahora, con este conocimiento, puedes elegir la herramienta adecuada para manejar errores en tus proyectos, dependiendo del tipo de operación que estés manejando y del contexto en el que te encuentres. Sin embargo, es importante notar que estos contenidos no reemplazan la utilidad de otros mecanismos de manejo de errores como ``try-catch`` o el uso de excepciones en casos específicos, sino que complementan y enriquecen la forma en que manejamos los errores en nuestros programas.
